on: [push]

name: Continuous integration

jobs:
  check:
    name: Check, build release and store
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v1
        with: 
          name: telepublish
          path: target/release/telepublish